server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin-spring-db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user
    password: user
  application:
    name: adminSpringBoot
